# default labels provided by Github Platform
- name: bug
  description: Something isn't working
  color: d73a4a
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: enhancement
  description: New feature or request
  color: a2eeef
- name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: question
  description: Further information is requested
  color: d876e3
- name: wontfix
  description: This will not be worked on
  color: ffffff

# Own labels used by Dependabot(bot) configuration
- name: dependencies
  description: Pull requests that update a dependency file
  color: d4c5f9
- name: javascript
  description: Pull requests that update Javascript code
  color: 168700
- name: test_local
  description: Does the local distribution work?
  color: ffff00
