# default labels provided by Github Platform
- name: bug
  description: Something isn't working
  color: d73a70
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: enhancement
  description: New feature or improvement to existing functionality
  color: a2eeef
- name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: question
  description: Further information is requested
  color: d876e3
- name: wontfix
  description: This will not be worked on
  color: ffffff

# Own labels used by Dependabot(bot) configuration
- name: dependencies
  description: Pull requests that update a dependency file
  color: d4c5f9
- name: 'awaiting triage'
  description: Check and prepare for development
  color: c0c0c0

# Labels inspired by https://opensource.creativecommons.org/contributing-code/repo-labels/
# Group: Aspect
- name: 'aspect:repo'
  description: Concerns the health of the repository (e.g. assets, documentation etc.)
  color: 04338c
  emoji: '📄'
- name: 'aspect:api'
  description: Concerns the API layer (or backend) of the software
  color: 04338c
  emoji: '💻'
- name: 'aspect:dx'
  description: Concerns developers' experience with the codebase
  color: 04338c
  emoji: '🤖'
- name: 'aspect:ui'
  description: Concerns end-users' experience with the software
  color: 04338c
  emoji: '🕹'

# Group: Priority
- name: 'priority: critical'
  description: Must be fixed ASAP
  color: b60205
- name: 'priority: high'
  description: Stalls work on the project or its dependents
  color: ff9f1c
- name: 'priority: medium'
  description: Not blocking but should be fixed soon
  color: ffcc00
- name: 'priority: low'
  description: Low priority and doesn't need to be rushed
  color: cfda2c

# Labels inspired by https://github.com/s4u/.github/blob/master/.github/labels.yml
- name: 'code quality'
  description: Improvements, refactoring or code cleanups
  color: 6ae2bc
- name: 'deprecation'
  description: Feature or some public api is made deprecated by this issue.
  color: 893636
- name: 'breaking changes'
  description: Feature of some public api is made incompatible by this issue.
  color: 7c1e1e

# Labels inspired by 'thinking on my own'
- name: 'deployment'
  description: The workflow run attempts to deploy the software artifact.
  color: a2ee88
- name: fix
  description: Fix something, which isn't working as expected.
  color: d73a4a  
