name: Distribute labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label_sync.yml
  workflow_dispatch:

jobs:
  label-sync-local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml

  label-sync-remote:
    strategy:
      fail-fast: false

      matrix:
        repo:
          - jfandy1982/dotfiles
          - jfandy1982/dotfiles-private
          - jfandy1982/education
          - jfandy1982/emby-data-check
          - jfandy1982/emby-data-check-backend
          - jfandy1982/emby-data-check-ui-angular-bootstrap
          - jfandy1982/emby-data-check-ui-angular-material
          - jfandy1982/emby-rest-api-data-sim
          - jfandy1982/find-duplicates
          - jfandy1982/jfandy1982
          - jfandy1982/test-connection
          - jfandy1982/vagrant-test-boxes
          - jfandy1982/webstation

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          repository: ${{ matrix.repo }}
          token: ${{ secrets.SYNC_LABELS }}
