name: Distribute labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label_sync.yml
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  label-sync-local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: brpaz/action-label-syncer@32e516ae73bbf7c7c0548897be07080795336e15 #v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml

  label-sync-remote:
    strategy:
      fail-fast: false

      matrix:
        repo:
          - jfandy1982/action-nx-affected-projects-and-deps
          - jfandy1982/dotfiles
          - jfandy1982/dotfiles-private
          - jfandy1982/education
          - jfandy1982/emby-data-check
          - jfandy1982/find-duplicates
          - jfandy1982/harznet
          - jfandy1982/jfandy1982
          - jfandy1982/node-format-flux
          - jfandy1982/pipeline-playground
          - jfandy1982/test-connection
          - jfandy1982/vagrant-test-boxes

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: brpaz/action-label-syncer@32e516ae73bbf7c7c0548897be07080795336e15 #v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          repository: ${{ matrix.repo }}
          token: ${{ secrets.SYNC_LABELS }}
